version: '2'
services:
  web:
    volumes:
     - ./app:/application
    networks:
     - backend
    ports:
     - "8080:8080"
  redis:
    image: "redis:alpine"
    cpu_shares: 128
    mem_limit: 134217728
    networks:
     - backend
networks:
  backend:


