version: '2'
services:
  web:
    image: 831650818513.dkr.ecr.us-east-1.amazonaws.com/xpeppers/aws-ecs-workshop:$TAG
    build:
      context: .
      args:
        TAG_VERSION_ARG: $TAG
    environment:
      - COLOR=green
      - TAG=$TAG
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
    cpu_shares: 128
    mem_limit: 134217728
